---
title: "MICB 405 Project 2"
author: "Shannah"
date: "November 17, 2018"
output:
  word_document: default
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE)
library(tidyr)
library(dplyr)
library(pathview)
library(tidyverse)

#If come across negative vector error then you should subset your data (for ex. by proteobar)
```

# Data
Load the data and put it in a format that I need for plotting
```{r}

#--- GETTING THE DATA ----
# Load raw data
raw_dat <- readr::read_csv("Saanich_Data.csv")

#Clean dat
dat <- 
  raw_dat %>%
  dplyr::filter(!is.na(WS_O2)) %>%
  dplyr::rename(O2_uM=WS_O2, NO3_uM=WS_NO3, H2S_uM=WS_H2S) %>%
  dplyr::mutate(Depth_m=Depth*1000)

# -- rpkm data --
#Read in KO Annotation tables
ko <- read.table("SaanichInlet_MAGs_ORFs_ko.cleaned.txt") %>% 
  dplyr::rename(orf = V1) %>% 
  dplyr::rename(ko = V2)

#Read in all rpkm files from each cruise in August
rpkm_48 <- read.table("SI048_200m.RPKM.csv", header=FALSE, sep=',') %>% 
  dplyr::rename(orf = V1) %>% 
  dplyr::rename(rpkm = V2)
rpkm_72 <- read.table("SI048_200m.RPKM.csv", header=FALSE, sep=',') %>% 
  dplyr::rename(orf = V1) %>% 
  dplyr::rename(rpkm = V2)
rpkm_73 <- read.table("SI073_200m.RPKM.csv", header=FALSE, sep=',') %>% 
  dplyr::rename(orf = V1) %>% 
  dplyr::rename(rpkm = V2)
rpkm_74 <- read.table("SI074_200m.RPKM.csv", header=FALSE, sep=',') %>% 
  dplyr::rename(orf = V1) %>% 
  dplyr::rename(rpkm = V2)
rpkm_75 <- read.table("SI075_200m.RPKM.csv", header=FALSE, sep=',') %>% 
  dplyr::rename(orf = V1) %>% 
  dplyr::rename(rpkm = V2)

#Read in prokka MAG map
prokka_mag_map <- read.table("Prokka_MAG_map_basename.csv", header=F, sep=',') %>% 
  dplyr::rename(prokka_id = V1) %>% 
  dplyr::rename(mag = V2)

#Read in gtdbtk files
arc_class <- read.table("gtdbtk.ar122.classification_pplacer.tsv", sep="\t")
bac_class <- read.table("gtdbtk.bac120.classification_pplacer.tsv", sep="\t")

#Combine archaea and bacteria gtdb files
gtdb_dat <- rbind(arc_class, bac_class) %>% 
  dplyr::rename(mag = V1) %>% 
  separate(V2, sep=';', into=c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species"))

#combine all cruises and ko values
ko_rpkm_48 <- left_join(ko, rpkm_48, by="orf") %>% 
  separate(orf, into=c("prokka_id", "orf_id")) %>% # Split the Prokka ORF names into MAG identifier and ORF
  left_join(prokka_mag_map, by="prokka_id") %>% 
  left_join(gtdb_dat, by="mag")
ko_rpkm_72 <- left_join(ko, rpkm_72, by="orf") %>% 
  separate(orf, into=c("prokka_id", "orf_id")) %>% # Split the Prokka ORF names into MAG identifier and ORF
  left_join(prokka_mag_map, by="prokka_id") %>% 
  left_join(gtdb_dat, by="mag")
ko_rpkm_73 <- left_join(ko, rpkm_73, by="orf") %>% 
  separate(orf, into=c("prokka_id", "orf_id")) %>% # Split the Prokka ORF names into MAG identifier and ORF
  left_join(prokka_mag_map, by="prokka_id") %>% 
  left_join(gtdb_dat, by="mag")
ko_rpkm_74 <- left_join(ko, rpkm_74, by="orf") %>% 
  separate(orf, into=c("prokka_id", "orf_id")) %>% # Split the Prokka ORF names into MAG identifier and ORF
  left_join(prokka_mag_map, by="prokka_id") %>% 
  left_join(gtdb_dat, by="mag")
ko_rpkm_75 <- left_join(ko, rpkm_75, by="orf") %>% 
  separate(orf, into=c("prokka_id", "orf_id")) %>% # Split the Prokka ORF names into MAG identifier and ORF
  left_join(prokka_mag_map, by="prokka_id") %>% 
  left_join(gtdb_dat, by="mag")

#Merge all cruises except for cruise 42 (from february)
#All cruises are from August except for Cruise 42 and b/c seasons can dramatically affect the water column AND we don't have enough data points to compare across seasons (only one from February) we are removing the February rpkm value.
ko_rpkm <- rbind(ko_rpkm_48, ko_rpkm_73, ko_rpkm_74, ko_rpkm_75)

# #Get all phylum
# lo_phylum <- unique(ko_rpkm$Phylum)
#
# 
# #add the rpkm values of rows the with same mag and ko values
# t_rpkm <- ko_rpkm %>% 
#   dplyr::group_by(mag, ko) %>% 
#   dplyr::summarise(total = sum(rpkm))


```

# Contamination vs Completeness Scatter Plot
First I will analyse the MAGs from checkM output with rpkm abundance values
```{r}

#TODO: include dotted lines to show ranges
#TODO: include the units on each axis (should be %)
#TODO: convert contamination to percentage ?!?!
#TODO: include a None lineage?
#TODO: include range labels

#Probably want to include as many MAGs as possible because we are wanting to fill in a pathway

#Load .tsv file from MetaBAT2 to dat
bin_dat <- read_tsv(file="MetaBAT2_SaanichInlet_200m_min1500_checkM_stdout.tsv", col_names = TRUE)

#Rename Marker lineage so it's one string (makes it easier later)
bin_dat <- bin_dat %>%
  dplyr::rename('Marker_lineage' = 'Marker lineage')

#Add new column with just lineage for point colors
bin_dat <- bin_dat %>%
  dplyr::mutate('lineage' = gsub(".*__(*)", "\\1", Marker_lineage),
                'lineage' = gsub("\\(|\\)", "", lineage),
                'lineage' = gsub("UID.*", "", lineage))


#Plotting Completeness vs Contamination of MAGs at 200m
bin_dat %>%
  ggplot(aes(x=Completeness, y=Contamination, colour=lineage)) +
  geom_point() +
  #added discrete scales ; palette from colorbrewer2 but added extra ("#969696") b/c 13 values
  scale_color_manual(values = c('#a6cee3','#1f78b4',"#b2df8a","#33a02c","#fb9a99",
                                "#e31a1c",'#fdbf6f',"#ff7f00","#cab2d6","#6a3d9a",
                                "#ffff99","#b15928", "#969696")) + 
  geom_vline(xintercept = 50, linetype = "dashed", size = 1, color = "#808080") + 
  geom_vline(xintercept = 70, linetype = "dashed", size = 1, color = "#808080") + #TODO: check what this value is
  geom_vline(xintercept = 90, linetype = "dashed", size = 1, color = "#808080") + #TODO: check what this value is
  geom_hline(yintercept = 50, linetype = "dashed", size = 1, color = "#808080") + #TODO: check what this value is
  geom_hline(yintercept = 70, linetype = "dashed", size = 1, color = "#808080") + #TODO: check what this value is
  geom_hline(yintercept = 90, linetype = "dashed", size = 1, color = "#808080")   #TODO: check what this value is

```

# Bubble Plot
Next I will create RPKM bubble-plot of each Nitrogen/Sulphur-cycling gene versus taxonomy
```{r}
#Read in pathways that map to their respective ko values 
ko00910 <- read_csv("ko_00910_values.csv")
ko01200 <- read_csv("ko_found_in_01200.csv")
ko00720 <- read_csv("ko_found_in_00720.csv")
ko00920 <- read_csv("ko_found_in_00920.csv")

t_rpkm <- ko_rpkm %>% 
  mutate(ko=as.character(ko)) %>%
  group_by(mag, ko, orf_id, Phylum) %>%
  summarise(total_rpkm = sum(rpkm))

#Combine each pathway with the t_rpkm by ko values
nitrogen <- dplyr::left_join(t_rpkm, ko00910, by = "ko") %>%
  dplyr::select(-pathway) %>%
  dplyr::filter(total_rpkm > 0)

#Map the ko values to the steps in the pathway (EC- Enzyme Nomenclature)
library(httr)
ko_ec <- lapply(nitrogen$ko, function(ko_val) {
  r <- GET(paste0("http://rest.kegg.jp/get/ko:", ko_val))
  result <- content(r, "parsed")
  pos = regexpr('EC', result)
  result <- substr(result, pos+3, nchar(result))
  pos = regexpr('PATHWAY', result)
  result <- substr(result, 0, pos-3)
  result
})

nitrogen %>%
  ggplot(aes(x=Phylum, y=orf_id, size = total_rpkm)) + 
  geom_point() + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1))


# bubble <- ggplot(fun_category_df, 
#                  aes(x =sec_category  , y = sec_function , size = `Number of Patents`)) %>%
#           + geom_point() + theme(axis.text.x = element_text(angle = 90, hjust = 1))

```



# Geochemical Gradients
```{r}
# Load raw data
raw_dat <- readr::read_csv("Saanich_Data.csv")

#Clean dat
dat <- 
  raw_dat %>%
  dplyr::select(Cruise, Date, Depth, Temperature,
         WS_O2, WS_NO3, WS_H2S) %>%
  dplyr::filter(!is.na(WS_O2)) %>%
  dplyr::rename(O2_uM=WS_O2, NO3_uM=WS_NO3, H2S_uM=WS_H2S) %>%
  dplyr::mutate(Depth_m=Depth*1000)


#want to create a plot with all 3 variables as x axis and depth as y with shape as type
#can manipulate data frame to do so
dat %>%
  dplyr::select(Depth_m, H2S_uM, NO3_uM, O2_uM) %>%
  gather(key = "Chemical", value = "Concentration", -Depth_m) %>%
  ggplot() +
  geom_point(aes(x=Concentration, y=Depth_m, shape=Chemical, colour=Chemical))
  

```


