---
title: "Pathview Aggregated by Class"
author: "Group 17"
date: "November 25, 2018"
output: html_document
---

```{r setup, warning=FALSE, message=FALSE}
library(tidyr)
library(dplyr)
library(pathview)
library(RColorBrewer)
library(knitr)
```

##Load in Data

```{r, read, warning=FALSE, message=FALSE}

#Read in KO Annotation tables
ko <- read.table("SaanichInlet_MAGs_ORFs_ko.cleaned.txt") %>% 
  dplyr::rename(orf = V1) %>% 
  dplyr::rename(ko = V2)

#Read in all rpkm files from each cruise
# Removing cruise from February (42)
# rpkm_42 <- read.table("SI042_200m.RPKM.csv", header=FALSE, sep=',') %>% 
#   dplyr::rename(orf = V1) %>% 
#   dplyr::rename(rpkm = V2)
rpkm_48 <- read.table("SI048_200m.RPKM.csv", header=FALSE, sep=',') %>% 
  dplyr::rename(orf = V1) %>% 
  dplyr::rename(rpkm = V2)
rpkm_72 <- read.table("SI048_200m.RPKM.csv", header=FALSE, sep=',') %>% 
  dplyr::rename(orf = V1) %>% 
  dplyr::rename(rpkm = V2)
rpkm_73 <- read.table("SI073_200m.RPKM.csv", header=FALSE, sep=',') %>% 
  dplyr::rename(orf = V1) %>% 
  dplyr::rename(rpkm = V2)
rpkm_74 <- read.table("SI074_200m.RPKM.csv", header=FALSE, sep=',') %>% 
  dplyr::rename(orf = V1) %>% 
  dplyr::rename(rpkm = V2)
rpkm_75 <- read.table("SI075_200m.RPKM.csv", header=FALSE, sep=',') %>% 
  dplyr::rename(orf = V1) %>% 
  dplyr::rename(rpkm = V2)

#Read in prokka MAG map
prokka_mag_map <- read.table("Prokka_MAG_map_basename.csv", header=F, sep=',') %>% 
  dplyr::rename(prokka_id = V1) %>% 
  dplyr::rename(mag = V2)

#Read in gtdbtk files
arc_class <- read.table("gtdbtk.ar122.classification_pplacer.tsv", sep="\t")
bac_class <- read.table("gtdbtk.bac120.classification_pplacer.tsv", sep="\t")

#Combine archaea and bacteria gtdb files
gtdb_dat <- rbind(arc_class, bac_class) %>% 
  dplyr::rename(mag = V1) %>% 
  separate(V2, sep=';', into=c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species"))

#checkm data
checkm_dat <- read.table("MetaBAT2_SaanichInlet_200m_min1500_checkM_stdout.tsv",
                         header=TRUE,
                         sep="\t",
                         comment.char = '') %>% 
  dplyr::rename(mag = Bin.Id) %>% 
  dplyr::select(mag, Completeness, Contamination)

# Due to a bug in the renaming script we have to rename the bins. Its a bit hacky but works using tidyverse functions
metag_rpkm <- read.table("SaanichInlet_200m_binned.rpkm.csv", header=T, sep=',') %>% 
  mutate(Sequence = gsub('m_', 'm.', Sequence)) %>% 
  mutate(Sequence = gsub('Inlet_', 'Inlet.', Sequence)) %>% 
  separate(col=Sequence, into=c("mag", "contig"), sep='_', extra="merge") %>% 
  group_by(Sample, mag) %>% 
  summarise(g_rpkm = mean(RPKM)) %>% 
  mutate(mag = gsub('Inlet.', 'Inlet_', mag))

#Determine the number of Class present in our bins, and how many MAGs are representing each. 
gtdb_dat %>% 
  group_by(Class) %>% 
  summarise(count = n_distinct(mag)) %>% 
  kable()
gtdb_dat <- dplyr::select(gtdb_dat, mag, Kingdom, Phylum, Class, Order, Family)
```

##More Data Modifications

```{r, arrange, warning=FALSE, message=FALSE}
ko_rpkm_48 <- left_join(ko, rpkm_48, by="orf") %>% 
  separate(orf, into=c("prokka_id", "orf_id")) %>% # Split the Prokka ORF names into MAG identifier and ORF
  left_join(prokka_mag_map, by="prokka_id") %>% 
  left_join(gtdb_dat, by="mag") %>%
  left_join(checkm_dat, by="mag") %>%
  left_join(metag_rpkm, by="mag")
ko_rpkm_72 <- left_join(ko, rpkm_72, by="orf") %>% 
  separate(orf, into=c("prokka_id", "orf_id")) %>% # Split the Prokka ORF names into MAG identifier and ORF
  left_join(prokka_mag_map, by="prokka_id") %>% 
  left_join(gtdb_dat, by="mag")%>%
  left_join(checkm_dat, by="mag") %>%
  left_join(metag_rpkm, by="mag")
ko_rpkm_73 <- left_join(ko, rpkm_73, by="orf") %>% 
  separate(orf, into=c("prokka_id", "orf_id")) %>% # Split the Prokka ORF names into MAG identifier and ORF
  left_join(prokka_mag_map, by="prokka_id") %>% 
  left_join(gtdb_dat, by="mag")%>%
  left_join(checkm_dat, by="mag") %>%
  left_join(metag_rpkm, by="mag")
ko_rpkm_74 <- left_join(ko, rpkm_74, by="orf") %>% 
  separate(orf, into=c("prokka_id", "orf_id")) %>% # Split the Prokka ORF names into MAG identifier and ORF
  left_join(prokka_mag_map, by="prokka_id") %>% 
  left_join(gtdb_dat, by="mag")%>%
  left_join(checkm_dat, by="mag") %>%
  left_join(metag_rpkm, by="mag")
ko_rpkm_75 <- left_join(ko, rpkm_75, by="orf") %>% 
  separate(orf, into=c("prokka_id", "orf_id")) %>% # Split the Prokka ORF names into MAG identifier and ORF
  left_join(prokka_mag_map, by="prokka_id") %>% 
  left_join(gtdb_dat, by="mag")%>%
  left_join(checkm_dat, by="mag") %>%
  left_join(metag_rpkm, by="mag")

#We want to join all of the cruises together
rpkm_dat <- rbind(ko_rpkm_48, ko_rpkm_73, ko_rpkm_74, ko_rpkm_75)

head(rpkm_dat) %>% kable()

```


##More Data Changes for Pathview Input
```{r subsetting, warning=FALSE, message=FALSE}

# Aggregate by Class, and mean RPKM of each KO number.
lo_classes <- unique(rpkm_dat$Class)

lo_rpkm_mat <- lapply(lo_classes, function(class) {
  t_rpkm <- rpkm_dat %>%
    dplyr::filter(Class == class) %>%
    dplyr::group_by(Class, ko) %>% 
    dplyr::summarise(t_rpkm = mean(rpkm)) %>% 
    spread(key = Class, value = t_rpkm)
    
  pv_mat <- dplyr::select(t_rpkm, -ko)
  rownames(pv_mat) <- t_rpkm$ko
  return(pv_mat)
})


#Name each element in the list according to the class (for organization)
names(lo_rpkm_mat) <- lo_classes

#For a single pathview output that is grouped by class
t_rpkm <- rpkm_dat %>%
  dplyr::group_by(Class, ko) %>% 
  dplyr::summarise(t_rpkm = mean(rpkm)) %>% 
  spread(key = Class, value = t_rpkm)
  
pv_mat <- dplyr::select(t_rpkm, -ko)
rownames(pv_mat) <- t_rpkm$ko

```

##Pathview

We will be viewing the sulfur metabolic pathway

color scale using [colorbrewer2] (http://colorbrewer2.org/#type=sequential&scheme=BuGn&n=3). 

```{r, pathviewing, warning=FALSE, message=FALSE}
lo_classes <- unique(rpkm_dat$Class)

# Sulfur metabolism pathview for each class
# We change the working dir so pathview prints into different folders in the loop 
lo_pv.out_class <- lapply(lo_classes, function(class) {
  setwd(paste0("C:/Users/Shannah/OneDrive/Uni-Year-5/MICB_405/Project2/pathview_output/", class, "/"))
  pathview(gene.data = lo_rpkm_mat[[class]],
           limit = list(gene = c(0,10)),
           low = list(gene = "#91bfdb"),
           mid = list(gene = "#ffffbf"),
           high = list(gene = "#fc8d59"),
           species = "ko",
           pathway.id="00920",
           kegg.dir=".")

})

# Sulfur metabolism pathview grouped by class
pv.out <- pathview(gene.data = pv_mat,
                   limit = list(gene = c(0,10)),
                   low = list(gene = "#91bfdb"),
                   mid = list(gene = "#ffffbf"),
                   high = list(gene = "#fc8d59"),
                   species = "ko",
                   pathway.id="00920",
                   kegg.dir = ".")

```



